use std::ops::{Index, IndexMut};

use crate::bit_accessors;
use crate::core::MemoryMappedRegister;

pub const SELECT_BUTTONS: u8 = 0x20;
pub const SELECT_DIRECTIONS: u8 = 0x10;
pub const INPUT_DOWN_START: u8 = 0x08;
pub const INPUT_UP_SELECT: u8 = 0x04;
pub const INPUT_LEFT_B: u8 = 0x02;
pub const INPUT_RIGHT_A: u8 = 0x01;

/// # Joypad Input
/// It uses 6 GPIO pins to read the state of the buttons.
/// | P14   | P15    |     |
/// | ----- | ------ | --- |
/// | Down  | Start  | P13 |
/// | Up    | Select | P12 |
/// | Left  | B      | P11 |
/// | Right | A      | P10 |
#[derive(Debug, Default)]
pub struct Joypad(u8);

impl Joypad {
    bit_accessors! {
        target: 0;

        SELECT_BUTTONS,
        SELECT_DIRECTIONS,
        INPUT_DOWN_START,
        INPUT_UP_SELECT,
        INPUT_LEFT_B,
        INPUT_RIGHT_A
    }
}

impl MemoryMappedRegister for Joypad {}

impl Index<u16> for Joypad {
    type Output = u8;

    fn index(&self, _addr: u16) -> &Self::Output { &self.0 }
}

impl IndexMut<u16> for Joypad {
    fn index_mut(&mut self, _addr: u16) -> &mut Self::Output { &mut self.0 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    /// To test getters and setters generated by the macro `bit_accessors!`
    fn test_get_and_set() {
        let joypad = Joypad(SELECT_BUTTONS | INPUT_UP_SELECT);

        assert!(joypad.select_buttons());
        assert!(!joypad.select_directions());
        assert!(!joypad.input_down_start());
        assert!(joypad.input_up_select());
        assert!(!joypad.input_left_b());
        assert!(!joypad.input_right_a());
    }
}
