name: Release SD image

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://nixos-raspberrypi.cachix.org
            extra-trusted-public-keys = nixos-raspberrypi.cachix.org-1:4iMO9LXa8BqhU+Rpg6LQKiGa2lsNh/j2oiYLNOQ5sPI=
            connect-timeout = 5

      - name: Build SD image
        run: nix build .#installerImages.gbeed02 --print-build-logs

      - name: Prepare release asset
        run: cp result/sd-image/gbeed02.img.zst gbeed02.img.zst

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: gbeed02.img.zst
